#%RAML 1.0 Trait
usage: Authorization
headers:
  client_id:
    type: string
    required: true
    description: To authenticate system API
  client_secret:
    description: To authenticate system API
    type: string
    required: true  